config/routes.rb
MistEngine::Application.routes.draw do
  resources :groups
  resources :users

  root to: 'home#index'

  resources :articles, only: [:index, :show]
  constraints({ type: Regexp.new(Article::URL_TYPES.join('|')), id: /\d+/, slug: /[a-z0-9\-\_]+/ }) do
    get '/:type/:id-:slug' => 'articles#show'
    delete '/:type/:id-:slug' => 'articles#destroy'
    patch '/:type/:id-:slug' => 'articles#update'
  end

  namespace :admin do
    resources :covers
    resources :articles
  end
end

app/models/cover.rb
class Cover < ActiveRecord::Base
  belongs_to :article
  mount_uploader :image, CoverImageUploader

  validates_presence_of :image
  validate :article_or_url
  validate :url_details

  scope :active, -> { where(active: true) }
  scope :front_page, lambda { |count = 3|
    active.limit(count).order('weight ASC')
    .joins('LEFT JOIN `articles` ON `articles`.`id` = `covers`.`article_id`')
    .load
  }

  after_save :sweep_cache

  private

  def article_or_url
    errors[:base] << I18n.t('covers.errors.article-or-url-error') unless article_id.present? || url.present?
  end

  def url_details
    errors[:base] << I18n.t('covers.errors.title-description-error') if url.present? && (title.blank? || description.blank?)
  end

  def sweep_cache
    new_covers = Cover.front_page
    new_covers.each(&:touch)
    Rails.cache.write 'index-covers', new_covers
  end
end

app/controllers/admin/covers_controller.rb
class Admin::CoversController < ApplicationController
  before_action :set_cover, only: [:show, :edit, :update, :destroy]

  def index
    @covers = Cover.all
  end

  def show
  end

  def new
    @cover = Cover.new
  end

  def edit
  end

  def create
    @cover = Cover.new(cover_params)

    respond_to do |format|
      if @cover.save
        format.html { redirect_to admin_covers_path, notice: 'Cover was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @cover.update(cover_params)
        format.html { redirect_to admin_covers_path, notice: 'Cover was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @cover.destroy
    redirect_to admin_covers_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cover
    @cover = Cover.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow
  # the white list through.
  def cover_params
    params.require(:cover).permit(:article_id, :title, :url, :description,
                                  :active, :weight, :image)
  end
end

app/helpers/covers_helper.rb
module CoversHelper
end

app/views/covers/_cover.html.erb
<% cache cover do %>
<article class="<%= @covers.length > 2 ? cycle('headline', 'feature', 'feature') : cycle('headline', 'big feature') -%> coverstory" style="background-image: url(<%= @covers.length > 2 ? cover.image.url(current_cycle.to_sym) : cover.image.url(:headline) %>?<%= Time.now.to_i.to_s %>)">
  <h2><%= cover.title %></h2>
  <div class="cover-blurb"><%= cover.description %></div>
</article>
<% end %>

app/views/covers/_form.html.erb
<%= form_for(@cover) do |f| %>
  <% if @cover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cover.errors.count, "error") %> prohibited this cover from being saved:</h2>

      <ul>
      <% @cover.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.number_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/covers/index.html.erb
<h1>Listing covers</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Title</th>
      <th>Url</th>
      <th>Description</th>
      <th>Active</th>
      <th>Weight</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @covers.each do |cover| %>
      <tr>
        <td><%= cover.article_id %></td>
        <td><%= cover.title %></td>
        <td><%= cover.url %></td>
        <td><%= cover.description %></td>
        <td><%= cover.active %></td>
        <td><%= cover.weight %></td>
        <td><%= link_to 'Show', cover %></td>
        <td><%= link_to 'Edit', edit_cover_path(cover) %></td>
        <td><%= link_to 'Destroy', cover, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cover', new_cover_path %>

app/views/covers/new.html.erb
<h1>New cover</h1>

<%= render 'form' %>

<%= link_to 'Back', covers_path %>

app/views/covers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @cover.article_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @cover.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @cover.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cover.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @cover.active %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @cover.weight %>
</p>

<%= link_to 'Edit', edit_cover_path(@cover) %> |
<%= link_to 'Back', covers_path %>